package life.community.model;

public class QuestionTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_TAG.ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_TAG.QUESTION_ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_TAG.TAG_ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    private Long tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_TAG.GMT_CREATE
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION_TAG.GMT_MODIFIED
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_TAG.ID
     *
     * @return the value of QUESTION_TAG.ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_TAG.ID
     *
     * @param id the value for QUESTION_TAG.ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_TAG.QUESTION_ID
     *
     * @return the value of QUESTION_TAG.QUESTION_ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_TAG.QUESTION_ID
     *
     * @param questionId the value for QUESTION_TAG.QUESTION_ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_TAG.TAG_ID
     *
     * @return the value of QUESTION_TAG.TAG_ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_TAG.TAG_ID
     *
     * @param tagId the value for QUESTION_TAG.TAG_ID
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_TAG.GMT_CREATE
     *
     * @return the value of QUESTION_TAG.GMT_CREATE
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_TAG.GMT_CREATE
     *
     * @param gmtCreate the value for QUESTION_TAG.GMT_CREATE
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION_TAG.GMT_MODIFIED
     *
     * @return the value of QUESTION_TAG.GMT_MODIFIED
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION_TAG.GMT_MODIFIED
     *
     * @param gmtModified the value for QUESTION_TAG.GMT_MODIFIED
     *
     * @mbg.generated Sun Sep 15 13:36:21 GMT+08:00 2024
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}