server:
  port: 8887

github:
  client:
    id: Ov23liijchVoPwBKVJUY
    secret: e6e99db09c497e6105cc6668f4f7c59f5b8854da
  redirect:
    uri: http://localhost:8887/callback

Spring:
  datasource:
    url: jdbc:h2:~/MyPractice-community/community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: h2



